---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lucky_dev?useUnicode=yes&characterEncoding=UTF-8
    username: daniel
    password: P@s$w0rd123!
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    hibernate:
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true
server:
  port: 8089
sentry:
  enabled: true
  environment: development
prefix_game: s1_

kafka-service:
  url: http://localhost:8088/api/v1/ticket-bonus/

---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lucky?useUnicode=yes&characterEncoding=UTF-8
    username: daniel
    password: P@s$w0rd123!
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    hibernate:
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true
server:
  port: 8089
sentry:
  enabled: true
  environment: production
prefix_game: s1_

kafka-service:
  url: http://localhost:8088/api/v1/ticket-bonus/
